[package]
name = "neodymium"
version = "0.0.1"
edition = "2024"

[dependencies]
gpui = { version = "0.2.2", optional = true }
gpui-component = { version = "0.4.0", optional = true }
anyhow = { version = "1", optional = true }
